### ISSUE TITLE
Two memory leaks in kakuro

### ISSUE THREAD

**Issue by SteffenBauer** [Anders-Holst/sgt-puzzles-aho-extensions#1]
The function `pair *simple_evolve()` has two memory leaks, `accvec1` and `vec2`.
`accvec1` is simply never deallocated.
`vec2` is constantly dupstr'd in the `do{vec2 = mutate_answer(...)} while` loop, and also never deallocated.

Proposed solution:
- `accvec1` should just be sfree'd at the end of the function with `sfree(accvec1);`
- `vec2` is trickier, perhaps best to rewrite the `do{} while` loop into a `while {}` loop, even when this leads to code duplication:
```
vec2 = mutate_answer(kb, rs, MUTATION_RATE, kb->phase == 1 ? 0 : accvec1);
while (!strcmp(vec1, vec2)) {
    sfree(vec2);
    vec2 = mutate_answer(kb, rs, MUTATION_RATE, kb->phase == 1 ? 0 : accvec1);
}
```

**Comment by Anders-Holst** [comment]
Thanks for detecting this!
(I usually try to run valgrind on any code I release, but this was written a while ago and I must have slipped. I found a similar leak in alphacrypt, and a potential memory fault in supermaze, when checking all the code with valgrind now.)
I have now updated the code to solve these problems.
