### ISSUE TITLE
"Pencil auto-fill" in Kakuro odd/even mode fills wrong type of pencil numbers

### ISSUE THREAD

**Issue by SteffenBauer** [Anders-Holst/sgt-puzzles-aho-extensions#2]
Dark cells in odd/even kakuro mode accept only even numbers, white cells only odd numbers.

Entering pencil marks manually also only accepts the correct type of number.

But pressing "M" fills in exactly the wrong type of number (odd numbers in dark, even numbers in white cells).

Fix should be easily made by swapping `oddmask` and `evenmask` at line 2502 in function `execute_move()`

**Comment by Anders-Holst** [comment]
Thanks for detecting this! I have corrected it now.

(Apparently I don't use "M" often myself. It is included just because it seemed to be a "standard control". For Kakuro, as for Alphacrypt, I find it more useful to interpret pencil marks as a range, only writing the smallest and largest possible number. But I realize than in odd-even mode it might be useful. My favorite mode is otherwise No-same-combo. Did you try it yet?)

 / Anders

**Comment by SteffenBauer** [comment]
Ok. I am currently porting kakuro to my port of the puzzle collection for PocketBook eReaders. I have a dedicated screen button there for the operation "M" for filling out pencil marks, and it catched my attention during testing that it fills the marks on just the other way round than expected.

On another note, a question about the code, about lines 2702-2706, 2715-2717, and lines 2775-2782 in `draw_tile`: What exactly is the purpose of `if (tile & DF_DIGIT_MASK)`, and the draw operation in these code blocks? Is it connected with drawing numbers during input of multi-digit numbers?

**Comment by Anders-Holst** [comment]
Aha, nice! 

Yes, those lines are for the multi digit input. While pressing the first digit, it shows as e.g "1_" for a second while waiting for the second digit, as you have noticed. The DF_HAS_DIGIT_MASK bit is not yet set, but the DF_DIGIT_MASK bits are reused for storing the first digit during this time. So if the former is not set, but the second is, then we know we have a pending multi-digit. I don't remember exactly now how the magic on line 2716 works, but it is to make sure that such a pending multidigit is counted correctly when figuring out the needed pencil mark positions.

I suppose that on the e-book you may add direct buttons for the multidigits, and therefore you need to carefully remove or disable most of the multi-digit handling?

**Comment by Anders-Holst** [comment]
If so, I have a diff-file that may be of use. Not for kakuro directly but for keen, which i tried to add multi-digit support for, but the changes are analogous. If we can figure out a principled way of doing it on platforms where you just show more buttons, like phone, pad, or e-book, then it can be used also in keen, factor, alphacrypt, and maybe more.

The multi-digit handling was an additional reason for Simon to not want to include it. He wanted to figure out his own way of doing it. (Well, has he? No!)
